use_frameworks!
platform :ios, '8.0'


target 'SwiftGLES_Example' do
  pod 'SwiftGLES', :path => '../'
  #pod 'Charts' #, :git => 'http://ph.benemind.com/diffusion/CHART/chart.git'

  target 'SwiftGLES_Tests' do
    inherit! :search_paths
  end
end
